MiniStorage/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import Login, Logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('', include('main.urls'))
]

api/urls.py
from django.urls import path
from rest_framework import routers
from .views import ProductViewSet, ContractorViewSet, OperationViesSet, StorageItemViewSet, DocumentViewSet, \
    DocumentItemViewSet, contractor_categories, apply_document, unapply_document, remove_marked_objects, \
    import_products, consolidated_report, motion_report

app_name = 'api'

urlpatterns = [
    path('contractor_categories/', contractor_categories, name='contractor_categories'),
    path('apply_document/<int:document_id>/', apply_document, name='apply_document'),
    path('unapply_document/<int:document_id>/', unapply_document, name='unapply_document'),
    path('remove_marked_objects/', remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', import_products, name='import_products'),
    path('consolidated_report/', consolidated_report, name='consolidated_report'),
    path('motion_report/', motion_report, name='motion_report')
]

router = routers.SimpleRouter()
router.register('products', ProductViewSet, basename='products')
router.register('contractors', ContractorViewSet, basename='contractors')
router.register('operations', OperationViesSet)
router.register('documents', DocumentViewSet, basename='documents')
router.register('document_items', DocumentItemViewSet, basename='document_items')
router.register('storage_items', StorageItemViewSet, basename='storage_items')
urlpatterns.extend(router.urls)

main/urls.py
from django.urls import path
from .views import index, products, contractors, documents, operations, storage_items, products_to_xls, \
    contractors_to_xls, remove_marked_objects, import_products, consolidated_report, motion_report

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('products/', products, name='products'),
    path('contractors/', contractors, name='contractors'),
    path('documents/', documents, name='documents'),
    path('operations/', operations, name='operations'),
    path('storage_items/', storage_items, name='storage_items'),
    path('products_to_xls/', products_to_xls, name='products_to_xls'),
    path('contractors_to_xls/', contractors_to_xls, name='contractors_to_xls'),
    path('remove_marked_objects/', remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', import_products, name='import_products'),
    path('consolidated_report/', consolidated_report, name='consolidated_report'),
    path('motion_report/', motion_report, name='motion_report'),
]

main/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.http.response import FileResponse
from .models import Product, Contractor, Token
from utils import model_to_xls


class Login(LoginView):
    template_name = 'main/login.html'

    def get_success_url(self):
        user = self.request.user
        token = self.request.POST['user_token']
        Token.objects.update_or_create(user=user, defaults={'token': token})
        return super(Login, self).get_success_url()


class Logout(LogoutView):
    next_page = reverse_lazy('main:index')


@login_required(login_url='login')
def index(request):
    return render(request, 'main/index.html', context={})


@login_required(login_url='login')
def products(request):
    return render(request, 'main/products.html', context={})


@login_required(login_url='login')
def contractors(request):
    return render(request, 'main/contractors.html', context={})


@login_required(login_url='login')
def documents(request):
    return render(request, 'main/documents.html', context={})


@login_required(login_url='login')
def operations(request):
    return render(request, 'main/operations.html', context={})


@login_required(login_url='login')
def storage_items(request):
    return render(request, 'main/storage_items.html', context={})


@login_required(login_url='login')
def products_to_xls(request):
    column_descriptions = [
        {'machine_name': 'id', 'display_name': 'Номер'},
        {'machine_name': 'title', 'display_name': 'Наименование', 'width': 80},
        {'machine_name': 'description', 'display_name': 'Описание', 'width': 30},
        {'machine_name': 'price', 'display_name': 'Цена'},
        {'machine_name': 'dt_created', 'display_name': 'Дата создания', 'width': 30},
        {'machine_name': 'dt_updated', 'display_name': 'Дата изменения', 'width': 30},
    ]
    xls_data = model_to_xls(Product, column_descriptions)

    return FileResponse(
        xls_data,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        filename='products.xlsx'
    )


@login_required(login_url='login')
def contractors_to_xls(request):
    column_descriptions = [
        {'machine_name': 'id', 'display_name': 'Номер'},
        {'machine_name': 'title', 'display_name': 'Наименование', 'width': 80},
        {'machine_name': 'category', 'display_name': 'Категория', 'width': 30,
         'subs': dict(Contractor.CONTRACTOR_CATEGORY)},
        {'machine_name': 'dt_created', 'display_name': 'Дата создания', 'width': 30},
        {'machine_name': 'dt_updated', 'display_name': 'Дата изменения', 'width': 30},
    ]
    xls_data = model_to_xls(Contractor, column_descriptions)

    return FileResponse(
        xls_data,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        filename='products.xlsx'
    )


@login_required(login_url='login')
def remove_marked_objects(request):
    return render(request, 'main/remove_marked_objects.html', context={})


@login_required(login_url='login')
def import_products(request):
    return render(request, 'main/import_products.html', context={})


@login_required(login_url='login')
def consolidated_report(request):
    return render(request, 'main/consolidated_report.html', context={})


@login_required(login_url='login')
def motion_report(request):
    report_type = request.GET['report_type']
    return render(request, 'main/motion_report.html', context={'report_type': report_type})

main/templates/main/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/menu.css' %}">
    <link rel="stylesheet" href="{% static 'main/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'main/modals.css' %}">
    <link rel="stylesheet" href="{% static 'main/inputs.css' %}">
    <link rel="stylesheet" href="{% static 'main/content.css' %}">
    <link rel="stylesheet" href="{% static 'main/login.css' %}">
    <link rel="stylesheet" href="{% static 'main/search_elements.css' %}">
    <script src="{% static 'main/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'main/common.js' %}"></script>
    <title>MiniStorage</title>
</head>
<body>

{% block message %}
{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
{% endblock %}

{% block modals %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

main/templates/main/consolidated_report.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Сводный отчет по базе данных</strong></div>
    <div class="basic-div content-div" id="content-div">
        <p>Отправляю запрос на формирование отчета...</p>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiConsolidatedReportURL = "/api/consolidated_report/";
        let reportsDescriptions = [
            {
                key: "product_count",
                description: "Общее количество наименований товаров в справочнике"
            },
            {
                key: "contractor_count",
                description: "Общее количество наименований контрагентов в справочнике"
            },
            {
                key: "storage_item_count",
                description: "Общее количество наименований товаров на складе"
            },
            {
                key: 'total_cost',
                description: "Общая стоимость товаров на складе"
            }
        ]

        let $contentDiv = $("#content-div");

        $.ajax(apiConsolidatedReportURL, {
            "method": "GET",
            "dataType": "json",
            "success": function (data) {
                $contentDiv.empty();

                for (let {key, description} of reportsDescriptions) {
                    $contentDiv.append(
                        $("<p>")
                            .addClass("report-block")
                            .append($("<strong>").text(description + ": "))
                            .append($("<span>").text(data[key]))
                    );
                }
            },
            "error": function (jqXHR) {
                $contentDiv.empty();
                showAjaxError(jqXHR);
            }
        });
    </script>
{% endblock %}

main/templates/main/contractors.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Справочник контрагентов</strong></div>
    <div class="basic-div content-div" id="content-div">
        <div class="operation-div">
            <span class="span-button" id="create-button">Создать</span>
            <input type="text" name="search-field" id="search-field" value="">
            <span class="span-button" id="search-button">Найти</span>
            <span class="span-button" id="clear-search-field-button">Очистить</span>
        </div>
        <table id="content-table" class="content-table">
            <tr>
                <th column-key="id" display-name="Номер">Номер</th>
                <th column-key="title" display-name="Наименование">Наименование</th>
                <th column-key="category" display-name="Категория">Категория</th>
                <th column-key="dt_created" display-name="Дата создания">Дата создания</th>
                <th column-key="dt_updated" display-name="Дата изменения">Дата изменения</th>
                <th column-key="to_remove" display-name="Удл.">Удл.</th>
            </tr>
        </table>
        <div class="navigation-div">
            <span class="span-button" id="prev-page-button">Предыдущая страница</span>
            <span class="span-button" id="next-page-button">Следующая страница</span>
        </div>
    </div>
{% endblock %}

{% block modals %}
    <div class="modal" id="contractor-editor" style="display: none">
        <div>
            <div class="modal-control-buttons">
                <span class="span-button" id="contractor-editor-close-button">X</span>
            </div>
            <div>
                Номер: <span id="contractor-number"></span><br><br>
                Дата создания: <span id="contractor-dt-created"></span><br><br>
                Дата изменения: <span id="contractor-dt-updated"></span><br><br>
                <fieldset>
                    Наименование:<br><input type="text" name="contractor-title" id="contractor-title" value="" required><br><br>
                    Категория:
                    <select name="contractor-category" id="contractor-category"></select><br><br>
                    Пометить на удаление: <input type="checkbox" name="contractor-to-remove" id="contractor-to-remove">
                </fieldset>
            </div>
            <br>
            <div class="modal-control-buttons">
                <span class="span-button" id="contractor-editor-cancel-button">Отмена</span>
                <span class="span-button" id="contractor-editor-save-button">Сохранить</span>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiURL = "/api/contractors/";

        const apiContractorCategoriesURL = "/api/contractor_categories/";
        let contractorCategories = null;

        function checkContractorFormData() {
            if ($("#contractor-title").val().trim() === "") {
                throw new Error("Наименование не может быть пустым!")
            }
        }

        function showContractors(url) {
            if (!contractorCategories) {
                $.ajax(apiContractorCategoriesURL, {
                    "method": "GET",
                    "dataType": "json",
                    "async": false,
                    "success": function (data) {
                        contractorCategories = data;
                    }
                })
            }
            $.ajax(url, {
                "method": "GET",
                "dataType": "json",
                "success": function (data) {
                    let contractors, nextPage, prevPage;
                    if ("results" in data) {
                        contractors = data.results;
                        nextPage = data.next;
                        prevPage = data.previous;
                    } else {
                        contractors = [data];
                        nextPage = prevPage = null;
                    }

                    //Создаем таблицу со списком контрагентов
                    let $contentTable = $("#content-table");
                    $("tr:not(:first-child)", $contentTable).remove()
                    let $tableRow = null;
                    for (let contractor of contractors) {
                        formatDates(contractor);
                        $tableRow = $("<tr>");
                        $tableRow.append($("<td>").text(contractor.id));
                        $tableRow.append($("<td>").text(contractor.title));
                        $tableRow.append($("<td>").text(contractorCategories[contractor.category]));
                        $tableRow.append($("<td>").text(contractor.dt_created));
                        $tableRow.append($("<td>").text(contractor.dt_updated));
                        $tableRow.append($("<td>").text(contractor.to_remove ? "X" : "-"));
                        $tableRow.data("contractor", contractor);
                        $contentTable.append($tableRow);
                    }
                    $contentTable.on("click", "tr:not(:first-child)", contractorEdit);

                    createPaginationButtons(prevPage, nextPage, showContractors);
                },
                "error": function (jqXHR) {
                    showAjaxError(jqXHR, $("#contractor-editor"));
                }
            })
        }

        function contractorEdit() {
            let selectedContractor = $.data(this, "contractor");

            let $row = $(this);

            showModal($("#contractor-editor"));
            $("#contractor-number").text(selectedContractor.id);
            $("#contractor-dt-created").text(selectedContractor.dt_created);
            $("#contractor-dt-updated").text(selectedContractor.dt_updated);
            $("#contractor-title").val(selectedContractor.title);
            let categoriesList = [];
            for (let [key, value] of Object.entries(contractorCategories)) {
                categoriesList.push($("<option>").val(key).text(value));
                if (key === selectedContractor.category) {
                    categoriesList[categoriesList.length - 1].prop("selected", true);
                }
            }
            $("#contractor-category").empty().append(...categoriesList);
            $("#contractor-to-remove").prop("disabled", false);
            $("#contractor-to-remove").prop("checked", selectedContractor.to_remove);

            $("#contractor-editor-save-button").off().click(() => {
                //Проверяем корректность внесения данных в форму
                try {
                    checkContractorFormData();
                } catch (error) {
                    alert(error.message);
                    return;
                }

                let urlForRequest = `${apiURL}${selectedContractor.id}/`;
                $.ajax(urlForRequest, {
                    "method": "PATCH",
                    "dataType": "json",
                    "data": {
                        "title": $("#contractor-title").val(),
                        "category": $("#contractor-category").val(),
                        "to_remove": $("#contractor-to-remove:checked").val() ? true : false
                    },
                    "success": function (data) {
                        formatDates(data);

                        $row.empty();
                        $row.append($("<td>").text(data.id));
                        $row.append($("<td>").text(data.title));
                        $row.append($("<td>").text(contractorCategories[data.category]));
                        $row.append($("<td>").text(data.dt_created));
                        $row.append($("<td>").text(data.dt_updated));
                        $row.append($("<td>").text(data.to_remove ? "X" : "-"));
                        $row.data("contractor", data);

                        closeModal($("#contractor-editor"));
                    },
                    "error": function (jqXHR) {
                        showAjaxError(jqXHR, $("#contractor-editor"));
                    }
                })
            })
        }

        function contractorCreate() {
            showModal($("#contractor-editor"));

            $("#contractor-number").text("-");
            $("#contractor-dt-created").text("-");
            $("#contractor-dt-updated").text("-");
            $("#contractor-title").val("");
            let categoriesList = [];
            for (let [key, value] of Object.entries(contractorCategories)) {
                categoriesList.push($("<option>").val(key).text(value));
            }
            categoriesList[0].prop("selected", true);
            $("#contractor-category").empty().append(...categoriesList);
            $("#contractor-to-remove").prop("disabled", true);
            $("#contractor-to-remove").prop("checked", false);

            $("#contractor-editor-save-button").off().click(() => {
                try {
                    checkContractorFormData();
                } catch (error) {
                    alert(error.message);
                    return
                }

                $.ajax(apiURL, {
                    "method": "POST",
                    "dataType": "json",
                    "data": {
                        "title": $("#contractor-title").val(),
                        "category": $("#contractor-category").val()
                    },
                    "success": function (data) {
                        closeModal($("#contractor-editor"));
                        $("#search-field").val(data.id);
                        showContractors(`${apiURL}${data.id}`);
                    },
                    "error": function (jqXHR) {
                        showAjaxError(jqXHR, $("#contractor-editor"));
                    }
                })
            })
        }

        let contractorSearch = getSearchFunction(showContractors, getDefaultSearchParams, apiURL);

        let contractorSort = getSortFunction(showContractors, getDefaultSearchParams, apiURL);

        $("#clear-search-field-button").click(() => {
            $("#search-field").val("");
            contractorSearch();
        });
        $("#create-button").click(contractorCreate);
        $("#search-button").click(contractorSearch);
        $("#contractor-editor-close-button, #contractor-editor-cancel-button").click(() => closeModal($("#contractor-editor")));
        $("#content-table th").click(contractorSort);

        showContractors(apiURL);
    </script>
{% endblock %}

main/templates/main/import_products.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Импорт справочника товаров</strong></div>
    <div class="basic-div content-div" id="content-div">
        <p>
            Справочник товаров должен быть представлен в виде xlsx-файла со структурой, подобной приведенной ниже.
            Первая строка файла считается строкой-заголовком таблицы и игнорируется. Импорт идет до тех пор, пока не
            в файле не встретится первая пустая строка. Лист с данными о товарах дожен иметь имя "data".
            Импортированые товары будут добавлены в текущий справочник.
        </p>
        <table class="content-table">
            <tr>
                <th>Наименование</th>
                <th>Цена</th>
            </tr>
            <tr>
                <td>Товар 1</td>
                <td>1000</td>
            </tr>
            <tr>
                <td>Товар 2</td>
                <td>2000</td>
            </tr>
            <tr>
                <td>Товар 3</td>
                <td>1500</td>
            </tr>
        </table>
        <br>
        <div class="operation-div">
            Выберите файл: <input type="file" name="file" id="file" accept=".xlsx">
            <span class="span-button" id="import-button">Импортировать</span>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiImportProductsURL = "/api/import_products/";

        $("#import-button").click(() => {
            let file = $("#file").prop("files")[0];

            let formData = new FormData();
            formData.append("uploaded_file", file);

            $.ajax(apiImportProductsURL, {
                "method": "POST",
                "data": formData,
                "processData": false,
                "contentType": false,
                "success": function () {
                    showMessage("Файл успешно импортирован");
                },
                "error": function (jqXHR) {
                    showAjaxError(jqXHR);
                }
            })
        });
    </script>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base_template.html' %}

{% block message %}
    <div class="modal" id="message-block" style="display: none">
        <div>
            <div class="modal-control-buttons">
                <span class="span-button" id="message-block-close-button">X</span>
            </div>
            <div>
                <p></p>
            </div>
            <div class="modal-control-buttons">
                <span class="span-button" id="message-block-ok-button">Ок</span>
            </div>
        </div>
    </div>

    <script>
        $("#message-block-close-button, #message-block-ok-button").click(() => {
            closeModal($("#message-block"))
        });
    </script>
{% endblock %}





{% block menu %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
<style>
@media only screen and (min-width: 768px) {
 .dropdown:hover .dropdown-menu {
 display: block;
 margin-top: 0;
 }
}
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <a class="navbar-brand" href="#">BoxStock</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
 <span class="navbar-toggler-icon"></span>
 </button>

 <ul class="navbar-nav mr-auto">
  <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
 <span>
                    {% if user.first_name or user.last_name %}
                        {{ user.get_full_name }}
                    {% else %}
                        {{ user }}
                    {% endif %}
 </span>
   </a>
   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
    <!-- <div class="dropdown-divider"></div>-->
    <!-- <a class="dropdown-item" href="#">Something else here</a>-->
   </div>
  </li>

  <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Справочники
   </a>
   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="{% url 'main:products' %}">Товары</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:contractors' %}">Контрагенты</a>
   </div>
  </li>

  <li class="nav-item">
   <a class="nav-link" href="{% url 'main:documents' %}">Документы</a>
  </li>

  <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown_2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Отчеты
   </a>
   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="{% url 'main:consolidated_report' %}">Сводный отчет по базе данных</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:motion_report' %}?report_type=products">Отчет по движениям товаров</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:motion_report' %}?report_type=contractors">Отчет по операциям с контрагентами</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:products_to_xls' %}">Список товаров (XLS)</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:contractors_to_xls' %}">Список контрагентов (XLS)</a>

</div>
 </li>


  <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown_3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Сервисы
   </a>
   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="/admin/">Администрирование</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:remove_marked_objects' %}">Удаление помеченных объектов</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:import_products' %}">Импорт товаров</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:storage_items' %}">Управление остатками</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:storage_items' %}">Просмотр остатков</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'main:operations' %}">Журнал операций</a>

</div>
 </li>

 </ul>

 </div>
<!--/.nav-collapse -->
</nav>
<!--/.navbar -->


<script>
$('.dropdown-toggle').click(function(e) {
 if ($(document).width() > 768) {
 e.preventDefault();
 var url = $(this).attr('href');
 if (url !== '#') {
 window.location.href = url;
 }
 }
});
</script>

{% endblock %}

main/templates/main/login.html
{% extends 'main/base_template.html' %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

<style>
/* Demo Background */


/* Form Style */

.form-horizontal{
 background: #fff;
 padding-bottom: 40px;
 border-radius: 20px;
 text-align: center;
}
.form-horizontal .heading{
 display: block;
 font-size: 35px;
 font-weight: 700;
 padding: 35px 0;
 border-bottom: 1px solid #f0f0f0;
 margin-bottom: 30px;
}
.form-horizontal .form-group{
 padding: 0 40px;
 margin: 0 0 25px 0;
 position: relative;
}
.form-horizontal .form-control{
 background: #f0f0f0;
 border: none;
 border-radius: 20px;
 box-shadow: none;
 padding: 0 20px 0 45px;
 height: 40px;
 transition: all 0.3s ease 0s;
}
.form-horizontal .form-control:focus{
 background: #e0e0e0;
 box-shadow: none;
 outline: 0 none;
}
.form-horizontal .form-group i{
 position: absolute;
 top: 12px;
 left: 60px;
 font-size: 17px;
 color: #c8c8c8;
 transition : all 0.5s ease 0s;
}
.form-horizontal .form-control:focus + i{
 color: #00b4ef;
}
.form-horizontal .fa-question-circle{
 display: inline-block;
 position: absolute;
 top: 12px;
 right: 60px;
 font-size: 20px;
 color: #808080;
 transition: all 0.5s ease 0s;
}
.form-horizontal .fa-question-circle:hover{
 color: #000;
}
.form-horizontal .main-checkbox{
 float: left;
 width: 20px;
 height: 20px;
 background: #11a3fc;
 border-radius: 50%;
 position: relative;
 margin: 5px 0 0 5px;
 border: 1px solid #11a3fc;
}
.form-horizontal .main-checkbox label{
 width: 20px;
 height: 20px;
 position: absolute;
 top: 0;
 left: 0;
 cursor: pointer;
}
.form-horizontal .main-checkbox label:after{
 content: "";
 width: 10px;
 height: 5px;
 position: absolute;
 top: 5px;
 left: 4px;
 border: 3px solid #fff;
 border-top: none;
 border-right: none;
 background: transparent;
 opacity: 0;
 -webkit-transform: rotate(-45deg);
 transform: rotate(-45deg);
}
.form-horizontal .main-checkbox input[type=checkbox]{
 visibility: hidden;
}
.form-horizontal .main-checkbox input[type=checkbox]:checked + label:after{
 opacity: 1;
}
.form-horizontal .text{
 float: left;
 margin-left: 7px;
 line-height: 20px;
 padding-top: 5px;
 text-transform: capitalize;
}
.form-horizontal .btn{
 float: right;
 font-size: 14px;
 color: #fff;
 background: #00b4ef;
 border-radius: 30px;
 padding: 10px 25px;
 border: none;
 text-transform: capitalize;
 transition: all 0.5s ease 0s;
}
@media only screen and (max-width: 479px){
 .form-horizontal .form-group{
 padding: 0 25px;
 }
 .form-horizontal .form-group i{
 left: 45px;
 }
 .form-horizontal .btn{
 padding: 10px 20px;
 }
}
</style>

<div class="container">
    {% if user.is_authenticated %}
            Вы уже выполнили вход на сайт
            <a href="{% url 'main:index' %}">Перейти на главную страницу</a>
        {% else %}
    <div class="row">
    <div class="col-md-offset-3 col-md-6">
 <form class="form-horizontal" method="post">
 <span class="heading">Авторизация</span>

                {% csrf_token %}

               <div class="form-group">
 <input type="hidden" name="next" value="{{ next }}">
 <i class="fa fa-user"> {{ form.username }} </i>
 </div>
<br>
     <div class="form-group help">
 <input type="hidden" id="user-token" name="user_token" value="">
          <i class="fa fa-user"> {{ form.password }} </i>
 </div>
<br><br>
<button type="submit" class="btn btn-default">Вход</button>
            </form>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="loginErrorField">{{ error }}</p>
            {% endfor %}
            {% endif %}
        {% endif %}

    </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
        let tokenField = document.getElementById("user-token");
        let symbols = "0123456789qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM";
        let token = []
        for (let i = 0; i < 32; i++) token.push(symbols[Math.floor(Math.random() * symbols.length)]);
        token = token.join("");
        tokenField.value = token;
        localStorage.setItem("user_token", token)
    </script>
{% endblock %}